### PR TITLE
chore: extract tff example logic from the root mod

### PR DESCRIPTION
**Pull request by ferrarimarco**
Extract the distributed TFF example logic from the root Terraform module and put that in a dedicated scripts and README instructions. We're losing some automation, but we gain in modularity.

### CODE REVIEW

**Comment by laurentgrangeau** [comment]
Can you please rebase this PR against the main branch ? You have conflict in some of your files

**Comment by ferrarimarco** [comment]
@laurentgrangeau done :)

**Comment by ferrarimarco** [comment]
@laurentgrangeau ping :)

**Review by laurentgrangeau — APPROVED** [review]
LGTM

**Pull request merged**
